version: "3.3"

services:

  redis:
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    volumes: 
      - ./data/cache:/data

  django:
    restart: always
    build: ./src/backend/.
    command: bash -c "python ./manage.py migrate &&
      python ./manage.py createsuperuser --noinput &&
      daphne -b 0.0.0.0 -p 8000 backend.asgi:application"
    ports:
      - "8000:8000"
    volumes:
      - ./src/backend:/backend/
    environment:
      - "SECRET_KEY=${SECRET_KEY}" 
      - "DEBUG=${DEBUG}"
      - "DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}"
      - "DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}"
      - "DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}"
      - "HOST=${HOST}"

  nginx:
    image: nginx
    volumes:
      - ./src/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./src/nginx/logs:/var/log/nginx 
      - ./src/frontend:/usr/share/nginx/html 
    ports:
      - "80:80"
      - "443:443"
    