# Generated by Django 4.0.5 on 2022-06-09 19:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dshbd_name', models.CharField(max_length=30, verbose_name='Dashboard Name')),
                ('dshbd_description', models.CharField(max_length=100, verbose_name='Dashboard Description')),
                ('dshbd_users', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Dashboard Allowed Users')),
            ],
            options={
                'verbose_name': 'Dashboard',
                'ordering': ['dshbd_name'],
            },
        ),
    ]
