# Generated by Django 3.2.5 on 2022-06-24 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("datasocks", "0012_alter_datarecord_usersource"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dashboard",
            options={"ordering": ["id"], "verbose_name": "Dashboard"},
        ),
        migrations.AddField(
            model_name="machine",
            name="linked_dshbd",
            field=models.ForeignKey(
                default=13,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dashboard",
                to="datasocks.dashboard",
            ),
            preserve_default=False,
        ),
    ]
