# Generated by Django 3.2.5 on 2022-06-25 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("datasocks", "0014_auto_20220625_0043"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="machineaccessapikey",
            name="prefix",
        ),
        migrations.AlterField(
            model_name="machine",
            name="linked_dshbd",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="machine",
                to="datasocks.dashboard",
            ),
        ),
        migrations.AlterField(
            model_name="machineaccessapikey",
            name="machine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_key",
                to="datasocks.machine",
            ),
        ),
    ]
